### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by MikeGWem** [TabularLang/CoreTabular#8]
Just cloned the project to my local machine. Tried a build - failed with missing files Parser.fs and Lexer.fs and thus (presumably consequential) missing assembles Parsing.dll and tc.exe

Newb - so a quick pointer would be appreciated.

**Comment by crusso** [comment]
Are you using Linux\mono or Windows\VS?
If the later, you need to enable nuget package restore first so that VS can download the binaries to run the lex and yacc parser generators on Parser.fsy and Lexer.fsl to produce Parser.fs and Lexer.fs.

I've sometime had trouble getting this to work in VS, in which case running msbuild.exe from the visual studio command prompt works.

-c

**Comment by MikeGWem** [comment]
Hi - I am using VS2015. I have both options under NuGet Package Restore checked (Allow Nuget to download missing packages & Automatically check for missing packages during build)

I will try msbuild and see what I might see.

thanks for the prompt response by the way - much appreciated.

**Comment by MikeGWem** [comment]
looks like that was the answer - thanks I can get to it now (well start trying to figure it all out anyway)

**Comment by crusso** [comment]
You could also take  a look at the paper linked from the project website.

http://research.microsoft.com/en-us/projects/tabular/

The download for the Excel Add-in version of Tabular has a GettingStarted.docx plus some examples spreadsheet with models that might be useful. You don't need to have Excel to just look at them.

http://research.microsoft.com/en-us/downloads/0052e599-2f39-423d-8a55-798d5ce421cd/default.aspx

Best,
Claudio

**Comment by MikeGWem** [comment]
Thanks very much Claudio - I will follow up both.

have a great weekend,

mike
